# Generated by Django 4.2.6 on 2023-10-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Жанр', 'Жанр'), ('Боевик', 'Боевик'), ('Романтика', 'Романтика')], default=('Жанр', 'Жанр'), max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ReviewBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.TextField()),
                ('rate_stars', models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_object', to='book.book')),
            ],
        ),
    ]
